# Generated by Django 4.0.4 on 2022-05-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='imagen_album',
        ),
    ]
