# Generated by Django 4.0.4 on 2022-05-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_content_post_imagen_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_album',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
