# Generated by Django 4.0.4 on 2022-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_post_imagen_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_album',
            field=models.ImageField(upload_to='media'),
        ),
    ]
